In [3]:
import torch

"""
    Create the following tensors:
        1. 3D tensor of shape 20x30x40 with all values = 0
        2. 1D tensor containing the even numbers between 10 and 100
"""

tensor_3d = torch.zeros(30, 30, 40) 
tensor_1d = torch.arange(10, 101, 2)
print(tensor_3d)
print(tensor_1d)

tensor([[[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        [[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        [[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        ...,

        [[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0., 

In [16]:
"""
    x = torch.rand(4, 6)
    Calculate:
        1. Sum of all elements of x
        2. Sum of the columns of x  (result is a 6-element tensor)
        3. Sum of the rows of x   (result is a 4-element tensor)
"""
x = torch.rand(4, 6)
print(x)
print(x.shape)

sum_all = x.sum()
print(sum_all)

# columns (dim=0), rows (dim=1)
sum_cols = torch.sum(x, dim=0)
print(sum_cols)

sum_rows = torch.sum(x, dim=1)
print(sum_rows)

tensor([[0.7336, 0.7770, 0.0345, 0.7204, 0.9569, 0.1462],
        [0.6092, 0.9192, 0.0028, 0.8278, 0.0428, 0.9686],
        [0.0042, 0.6610, 0.8509, 0.5545, 0.7163, 0.8979],
        [0.4312, 0.0486, 0.5114, 0.6781, 0.2036, 0.3422]])
torch.Size([4, 6])
tensor(12.6390)
tensor([1.7782, 2.4059, 1.3996, 2.7809, 1.9197, 2.3548])
tensor([3.3687, 3.3705, 3.6848, 2.2151])


In [8]:
"""
    Calculate cosine similarity between 2 1D tensor:
    x = torch.tensor([0.1, 0.3, 2.3, 0.45])
    y = torch.tensor([0.13, 0.23, 2.33, 0.45])
"""
x = torch.tensor([0.1, 0.3, 2.3, 0.45])
y = torch.tensor([0.13, 0.23, 2.33, 0.45])

cosine_similarity = torch.nn.functional.cosine_similarity(x, y, dim=0)
print(cosine_similarity)

tensor(0.9995)


In [9]:
"""
    Calculate cosine similarity between 2 2D tensor:
    x = torch.tensor([[ 0.2714, 1.1430, 1.3997, 0.8788],
                      [-2.2268, 1.9799, 1.5682, 0.5850],
                      [ 1.2289, 0.5043, -0.1625, 1.1403]])
    y = torch.tensor([[-0.3299, 0.6360, -0.2014, 0.5989],
                      [-0.6679, 0.0793, -2.5842, -1.5123],
                      [ 1.1110, -0.1212, 0.0324, 1.1277]])
"""
x = torch.tensor([[ 0.2714, 1.1430, 1.3997, 0.8788],
                    [-2.2268, 1.9799, 1.5682, 0.5850],
                    [ 1.2289, 0.5043, -0.1625, 1.1403]])
y = torch.tensor([[-0.3299, 0.6360, -0.2014, 0.5989],
                    [-0.6679, 0.0793, -2.5842, -1.5123],
                    [ 1.1110, -0.1212, 0.0324, 1.1277]])

cosine_similarity = torch.nn.functional.cosine_similarity(x, y, dim=1) # columns (dim=0), rows (dim=1)
print(cosine_similarity)

tensor([ 0.4552, -0.3140,  0.9258])


In [15]:
"""
    x = torch.tensor([[ 0,  1],
                      [ 2,  3],
                      [ 4,  5],
                      [ 6,  7],
                      [ 8,  9],
                      [10, 11]])
    Make x become 1D tensor
    Then, make that 1D tensor become 3x4 2D tensor 
"""
x = torch.tensor([[ 0,  1],
                    [ 2,  3],
                    [ 4,  5],
                    [ 6,  7],
                    [ 8,  9],
                    [10, 11]])

print(x.shape)

# view method in PyTorch is used to reshape a tensor without changing its data
tensor_1d = x.view(-1)
print(tensor_1d)
print(tensor_1d.shape)

tensor_2d = x.view(3, 4)
print(tensor_2d)
print(tensor_2d.shape)

torch.Size([6, 2])
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
torch.Size([12])
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
torch.Size([3, 4])


In [ ]:
"""
    x = torch.rand(3, 1080, 1920)
    y = torch.rand(3, 720, 1280)
    Do the following tasks:
        1. Make x become 1x3x1080x1920 4D tensor
        2. Make y become 1x3x720x1280 4D tensor
        3. Resize y to make it have the same size as x
        4. Join them to become 2x3x1080x1920 tensor
"""

# torch.rand function in PyTorch generates a tensor filled with random numbers drawn from 
# a uniform distribution on the interval ([0, 1)).
x = torch.rand(3, 1080, 1920)
y = torch.rand(3, 720, 1280)

# unsqueeze method in PyTorch is used to add a singleton dimension (a dimension of size 1) 
# to a tensor at a specified position
tensor_x_4d = x.unsqueeze(0)
print(tensor_x_4d)
print(tensor_x_4d.shape)

tensor_y_4d = y.unsqueeze(0)
print(tensor_y_4d)
print(tensor_y_4d.shape)

# torch.nn.functional.interpolate function in PyTorch is used for resizing tensors
resized_y = torch.nn.functional.interpolate(tensor_y_4d, size=(1080, 1920), mode="bilinear", align_corners=False)
print(resized_y.shape)

# torch.cat function in PyTorch is used to concatenate (join) tensors along a specified dimension
concatenated_tensor = torch.concat((tensor_x_4d, resized_y), dim=0)
print(concatenated_tensor)
print(concatenated_tensor.shape)

tensor([[[[0.1988, 0.7988, 0.7694,  ..., 0.1909, 0.0912, 0.0341],
          [0.0336, 0.8306, 0.7410,  ..., 0.2502, 0.2544, 0.2148],
          [0.0683, 0.7969, 0.9576,  ..., 0.1406, 0.6662, 0.9199],
          ...,
          [0.8436, 0.9784, 0.8556,  ..., 0.0362, 0.4907, 0.7176],
          [0.2111, 0.1260, 0.8130,  ..., 0.8251, 0.9704, 0.7360],
          [0.0730, 0.0282, 0.4977,  ..., 0.6892, 0.3262, 0.3149]],

         [[0.9801, 0.8748, 0.1943,  ..., 0.0477, 0.3547, 0.5902],
          [0.4666, 0.1928, 0.7507,  ..., 0.9977, 0.2023, 0.1289],
          [0.2914, 0.9041, 0.0359,  ..., 0.1182, 0.2253, 0.5671],
          ...,
          [0.9236, 0.1257, 0.3322,  ..., 0.0434, 0.2708, 0.9755],
          [0.8176, 0.9305, 0.7250,  ..., 0.4590, 0.1757, 0.2768],
          [0.4847, 0.7720, 0.9188,  ..., 0.4349, 0.5843, 0.5685]],

         [[0.0476, 0.8762, 0.5678,  ..., 0.2414, 0.6461, 0.0930],
          [0.2818, 0.7393, 0.5937,  ..., 0.2383, 0.5308, 0.4688],
          [0.4634, 0.6723, 0.2074,  ..., 0

TypeError: concat() received an invalid combination of arguments - got (Tensor, Tensor, dim=int), but expected one of:
 * (tuple of Tensors tensors, int dim = 0, *, Tensor out = None)
 * (tuple of Tensors tensors, name dim, *, Tensor out = None)
